### ISSUE TITLE
客戶反映footer翻譯工具不見了~

### ISSUE THREAD

**Issue by doraliao611** [creatop/OT-System#2]
經查看，翻譯碼不見了，目前已加回去。

<div id="google_translate_element"></div><script type="text/javascript">
function googleTranslateElementInit() {
  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
}
</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

**Comment by creatopjason** [comment]
ok，如果處理完畢是否將 Issuse Close!!
